=== SigmaHQ/pySigma-validators-sigmaHQ/json-schema/schema_sigmahq_windows_validator.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
        "title": { "type": "string" },
        "version": { "type": "string" },
        "category_no_eventid": {
            "type":"array",
            "items": { "type": "string" }
        },
        "category_provider_name": {
            "type": "object",
            "additionalProperties": {
                "type":"array",
                "items": { "type": "string" }
            }
        }
    },
    "required": ["title","version","category_no_eventid","category_provider_name"]
}

=== SigmaHQ/pySigma-validators-sigmaHQ/tests/files/json/sigmahq_windows_validator.json
{
    "title": "Windows specific validator data pytests",
    "version": "20250101",
    "category_no_eventid": [
        "clipboard_capture",
        "create_remote_thread",
        "create_stream_hash"
    ],
    "category_provider_name": {
        "clipboard_capture": [
            "Microsoft-Windows-Sysmon"
        ],
        "create_remote_thread": [
            "Microsoft-Windows-Sysmon"
        ],
        "create_stream_hash": [
            "Microsoft-Windows-Sysmon"
        ]
    }
}

=== SigmaHQ/pySigma-validators-sigmaHQ/tools/sigmahq_windows_validator.json
{
  "title": "Windows specific validator data",
  "version": "20240809",
  "category_no_eventid": [
    "clipboard_capture",
    "create_remote_thread",
    "create_stream_hash",
    "dns_query",
    "driver_load",
    "file_access",
    "file_change",
    "file_delete",
    "file_event",
    "image_load",
    "network_connection",
    "pipe_created",
    "process_access",
    "process_creation",
    "process_tampering",
    "process_termination",
    "ps_classic_provider_start",
    "ps_classic_script",
    "ps_classic_start",
    "ps_module",
    "ps_script",
    "raw_access_thread",
    "registry_add",
    "registry_delete",
    "registry_rename",
    "registry_set",
    "sysmon_error",
    "sysmon_status"
  ],
  "category_provider_name": {
    "clipboard_capture": [
      "Microsoft-Windows-Sysmon"
    ],
    "create_remote_thread": [
      "Microsoft-Windows-Sysmon"
    ],
    "create_stream_hash": [
      "Microsoft-Windows-Sysmon"
    ],
    "dns_query": [
      "Microsoft-Windows-Sysmon"
    ],
    "driver_load": [
      "Microsoft-Windows-Sysmon"
    ],
    "file_access": [
      "Microsoft-Windows-Sysmon"
    ],
    "file_change": [
      "Microsoft-Windows-Sysmon"
    ],
    "file_delete": [
      "Microsoft-Windows-Sysmon"
    ],
    "file_event": [
      "Microsoft-Windows-Sysmon"
    ],
    "image_load": [
      "Microsoft-Windows-Sysmon"
    ],
    "network_connection": [
      "Microsoft-Windows-Sysmon",
      "Microsoft-Windows-TCPIP"
    ],
    "pipe_created": [
      "Microsoft-Windows-Sysmon"
    ],
    "process_access": [
      "Microsoft-Windows-Sysmon",
      "Microsoft-Windows-Kernel-Audit-API-Calls"
    ],
    "process_creation": [
      "Microsoft-Windows-Sysmon",
      "Microsoft-Windows-Security-Auditing",
      "Microsoft-Windows-Kernel-Process",
      "SystemTraceProvider-Process"
    ],
    "process_tampering": [
      "Microsoft-Windows-Sysmon"
    ],
    "process_termination": [
      "Microsoft-Windows-Sysmon"
    ],
    "ps_classic_provider_start": [
      "PowerShell"
    ],
    "ps_classic_script": [
      "PowerShell"
    ],
    "ps_classic_start": [
      "PowerShell"
    ],
    "ps_module": [
      "Microsoft-Windows-PowerShell"
    ],
    "ps_script": [
      "Microsoft-Windows-PowerShell"
    ],
    "raw_access_thread": [
      "Microsoft-Windows-Sysmon"
    ],
    "registry_add": [
      "Microsoft-Windows-Sysmon"
    ],
    "registry_delete": [
      "Microsoft-Windows-Sysmon"
    ],
    "registry_event": [
      "Microsoft-Windows-Sysmon"
    ],
    "registry_rename": [
      "Microsoft-Windows-Sysmon"
    ],
    "registry_set": [
      "Microsoft-Windows-Sysmon"
    ],
    "sysmon_error": [
      "Microsoft-Windows-Sysmon"
    ],
    "sysmon_status": [
      "Microsoft-Windows-Sysmon"
    ],
    "wmi_event": [
      "Microsoft-Windows-Sysmon"
    ]
  }
}
